---
- name: RedHat | add epel repo
  become: yes
  yum:
    name:
      - "{{ epel_package }}"
    state: latest
  environment: "{{proxy_env if proxy_env is defined else {}}}"

- name: RedHat | add CUDA repo
  yum_repository:
    name: cuda
    description: NVIDIA CUDA YUM Repo
    baseurl: "{{ nvidia_driver_rhel_cuda_repo_baseurl }}"
    gpgkey: "{{ nvidia_driver_rhel_cuda_repo_gpgkey }}"
  environment: "{{proxy_env if proxy_env is defined else {}}}"

- name: RedHat | install package
  package:
    name: "{{ dcgm_pkg_name }}"
    state: "present"
